Старков Дима
urfu-2016/markup-task-8 pull request #7
Opened 2016-11-27 22:53 UTC by dimastark

2016-11-27 22:54 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-28 06:13 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-29 17:35 UTC, bazhenova commented
Привет. Доделай, пожалуйста, требования задачи, а именно:
1) При клике на ссылку c рецептом карточка плавно разврачивается к нам «задней» стороной и увеличивается (создавая эффект «полета» к нам на встречу из экрана, макеты №4-6). Мы видим название блюда и рецепт (макет №7).
2) По клику на крестик анимация воспроизводится в обратном направлении, возвращая слайдер к состоянию до клика.

Сейчас эти требования не реализованы. Сделаешь -> начну проверять

2016-11-29 17:36 UTC, bazhenova commented
🍅

2016-11-30 06:25 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-30 06:35 UTC, bazhenova commented
Когда закрываю рецепт, остается ховер, хотя курсор вообще в другом месте

2016-11-30 06:41 UTC, bazhenova commented
![image](https://cloud.githubusercontent.com/assets/12410663/20742446/f36c6a90-b6f1-11e6-9b4e-65063fd729c1.png)
Если уменьшить размер экрана, то картинки находятся далеко друг от друга

2016-11-30 06:51 UTC, bazhenova commented on index.css
> +    content: 'Макет 2';
Не поняла, зачем это надо

2016-11-30 06:54 UTC, bazhenova commented on index.css
> +    width: calc(6 * 100% / 10 - 15px);
Ого, какие странные расчеты

2016-11-30 06:55 UTC, bazhenova commented on index.css
> +        transform: rotateX(0deg) scale(3, 2.5);
Вроде можно просто 0

2016-11-30 06:56 UTC, bazhenova commented on index.css
> +        transform: rotateX(0deg) scale(3, 2.5);
И не только тут

2016-11-30 06:57 UTC, bazhenova commented on index.css
> +/* Задание со звездочкой */
А где это задание со звездочкой можно посмотреть? Или ты его не доделал?

2016-11-30 07:00 UTC, bazhenova commented
В Firefox не работает ни ховер, ни рецепт 😞

2016-11-30 10:21 UTC, bazhenova commented
🍅

2016-11-30 11:26 UTC, dimastark commented on index.css
> +    content: 'Макет 2';
Было нужно, чтобы понимать, в каком режиме работает: доп или не доп

2016-11-30 11:26 UTC, dimastark commented on index.css
> +    width: calc(6 * 100% / 10 - 15px);
Торопился, двигал пиксели

2016-11-30 11:27 UTC, dimastark commented on index.css
> +        transform: rotateX(0deg) scale(3, 2.5);
WebStorm'у не нравится

2016-11-30 11:27 UTC, dimastark commented on index.css
> +/* Задание со звездочкой */
Доделал почти

2016-11-30 19:34 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-30 19:37 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-12-01 14:05 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-12-01 16:45 UTC, bazhenova commented
Когда тыкаю на следующую картинку, то после того, как она становится центральной, на ней остается ховер, хотя курсор в другом месте

2016-12-01 16:46 UTC, bazhenova commented
Замечание с Firefox ты не поправил

2016-12-01 16:50 UTC, bazhenova commented on index.css
> +    content: 'Инструкция:';
Лучше такие штуки не делать с помощью `before`

2016-12-01 17:54 UTC, bazhenova commented
Поправь замечания выше, тогда отдам ментору.

2016-12-01 17:55 UTC, bazhenova commented
🍅

2016-12-02 16:33 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-12-03 04:21 UTC, bazhenova commented
После правок в доп. задании получается вот такая штука 😞 
![image](https://cloud.githubusercontent.com/assets/12410663/20856772/aa518332-b939-11e6-8723-0f6b596c57a4.png)
Неправильная работа и при открытии и при закрытии

2016-12-03 04:21 UTC, bazhenova commented
🍅

2016-12-03 04:46 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-12-03 05:05 UTC, bazhenova commented
Еще вот такое бы неплохо поправить)
![bug](https://cloud.githubusercontent.com/assets/12410663/20856954/ca25049e-b93f-11e6-89e0-b9768df9d7d7.gif)

2016-12-03 05:07 UTC, bazhenova commented
А еще, когда тыкаю на рецепт, хотя карточка уже начала переворачиваться, остался ховер на пустом месте

2016-12-03 05:09 UTC, bazhenova commented
🍅

2016-12-03 06:24 UTC, dimastark commented
вроде как с расширением блока не поправить никак. Это из-за того, что резко меняется transform. В соседних ПР такая же бага была замечена, но сказали, что можно не править

2016-12-03 06:56 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-12-03 08:59 UTC, bazhenova commented
Ну это в соседних PR, а ты поправь) А в остальном вроде новых багов не появилось, молодец!

2016-12-03 08:59 UTC, bazhenova commented
🚀

2016-12-03 09:22 UTC, dimastark commented
Попытаюсь!

2016-12-04 16:12 UTC, VorontsovMaxim requested changes
🍅 
1. Анимация вылета карточки должна быть такой как на макете
2. Если нажать EXTRA, то обратно уже не вернуться

2016-12-04 16:12 UTC, VorontsovMaxim commented on index.html
> +    <link rel="stylesheet" type="text/css" href="index.css" class="veg-link">
Зачем здесь класс `.veg-link`?

2016-12-04 16:12 UTC, VorontsovMaxim commented on index.html
> +    <link rel="stylesheet" type="text/css" href="index.css" class="veg-link">
Зачем вообще этот класс и у элементов ниже, если в css его нет

2016-12-05 09:43 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-12-05 17:24 UTC, VorontsovMaxim approved these changes

2016-12-05 17:24 UTC, VorontsovMaxim commented
Принято

2016-12-05 17:24 UTC, closed without merging